#!/bin/ksh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

# =============================================================================
# =============================================================================
# slimcd_post_bootroot_pkg_image_mod
#
# pkg_image area modifications specific for slim cd, to be made after the
# bootroot is built.
# =============================================================================
# =============================================================================

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Main
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Perform pkg_image area modifications specific for slim cd after the
# bootroot is built.  This finalizer script is to be called after the bootroot
# build is complete.
# 
# Args:
#   MFEST_SOCKET: Socket needed to get manifest data via ManifestRead object
#
#   PKG_IMG_PATH: Package image area
#
#   TMP_DIR: Temporary directory to contain the bootroot file
#
# Of these automatically-passed variables, only the PKG_IMG_PATH is actually
# used.
#
# Note: This assumes bootroot is built and pkg_image area is intact.
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

if [ "$#" != "3" ] ; then
	print -u2 "Usage: $0: Requires 3 args:" \
	    "Reader socket, pkg_image mntpt, tmp dir"
	exit 1
fi

PKG_IMG_PATH=$2
if [ ! -d ${PKG_IMG_PATH} ] ; then
	print -u2 "$0: Image package area ${PKG_IMG_PATH} is not valid"
	exit 1
fi

# Remove the icon theme caches
print "Cleaning out icon theme cache"
if [ -d ${PKG_IMG_PATH}/usr ] ; then
	cd ${PKG_IMG_PATH}/usr
	/bin/find . -name icon-theme.cache -print|/bin/xargs rm
fi

exit 0
