#!/sbin/sh
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2008 Sun Microsystems, Inc.	 All rights reserved.
# Use is subject to license terms.
#
# Script to enable accessibility for the live CD.
#

. /lib/svc/share/smf_include.sh

if [ -f /.livecd ]
then
	# Determine if we should enable accessibility for the live CD
	# based upon the "-B assistive_tech" boot parameter.
	#
	assistive_tech=`prtconf -v /devices|sed -n '/assistive_tech/{;n;p;}'|cut -f 2 -d\'`

	if [ "x$assistive_tech" != "x" ]
	then
		# Allow the nwam GUI to participate in the accessibility
		# infrastructure.  This is because the nwam GUI is not
		# running as jack, but is instead running as root.
		#
		mv /lib/inet/nwamd /lib/inet/nwamd.bin
		cat << \NWAMD_EOF > /lib/inet/nwamd
#!/bin/sh
GTK_MODULES=gail:atk-bridge /lib/inet/nwamd.bin $*
NWAMD_EOF
		chmod +x /lib/inet/nwamd

		# Make it so things running as root can be seen by
		# assistive technologies.  This includes the nwam
		# GUI, for example.
		#
		cat << ORBITRC_EOF > /root/.orbitrc
ORBIIOPIPv4=1
ORBIIOPUNIX=0
ORBITRC_EOF

		# Enable accessibility for jack.
		#
		su jack -c "/usr/bin/gconftool-2 --type bool --set /desktop/gnome/interface/accessibility true"

		# Tell jack to autostart the appropriate assistive technology.
		#
		VISUAL_PREFIX="/desktop/gnome/applications/at/visual"
		GCONF="/usr/bin/gconftool-2"
		if [ "x$assistive_tech" = "xreader" ]
		then
			echo "enabling screen reader"
			su jack -c "$GCONF --type bool --set $VISUAL_PREFIX/startup true"
			su jack -c "$GCONF --type string --set $VISUAL_PREFIX/exec 'orca -n -e braille-monitor -d main-window'"
		elif [ "x$assistive_tech" = "xmagnifier" ]
		then
			echo "enabling screen magnifier"
			su jack -c "$GCONF --type bool --set $VISUAL_PREFIX/startup true"
			su jack -c "$GCONF --type string --set $VISUAL_PREFIX/exec 'orca -n -e magnifier -d speech -d main-window'"
		fi
	fi
fi

exit $SMF_EXIT_OK
