#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright (c) 2010, Oracle and/or its affiliates. All rights reserved.

# Copy /var/pkg to /tmp, to allow pkg(5) utilities to expand catalogs without
# running out of boot_archive space.  Copy symlinks as symlinks.
# Free unneeded space used in boot_archive.

# Copy the /var/pkg directory to /tmp/pkg.

. /lib/svc/share/smf_include.sh

OLD_DIR=/var/pkg
NEW_DIR=/tmp/pkg

cd $OLD_DIR
if [ $PWD != $OLD_DIR  ] ; then
	echo "Error finding $OLD_DIR" > /dev/msglog

	exit $SMF_EXIT_ERR_FATAL
fi

mkdir $NEW_DIR
if [ $? -ne 0 ] ; then
	echo "Error creating $NEW_DIR" > /dev/msglog

	exit $SMF_EXIT_ERR_FATAL
fi

find . -depth -print | cpio -pdum $NEW_DIR
if [ $? -ne 0 ] ; then
	echo "Error copying $OLD_DIR contents to $NEW_DIR" > /dev/msglog

	exit $SMF_EXIT_ERR_FATAL
fi

cd /
rm -rf $OLD_DIR
if [ $? -ne 0 ] ; then
	echo "Error removing original $OLD_DIR tree" > /dev/msglog

	exit $SMF_EXIT_ERR_FATAL
fi

ln -s $NEW_DIR $OLD_DIR
if [ $? -ne 0 ] ; then
	echo "Error making symlink from $OLD_DIR to $NEW_DIR" > /dev/msglog

	exit $SMF_EXIT_ERR_FATAL
fi

exit $SMF_EXIT_OK
