#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Copyright (c) 1984, 1986, 1987, 1988, 1989 AT&T.
# All rights reserved.
#
#

. /lib/svc/share/smf_include.sh
. /lib/svc/share/fs_include.sh

#
# Temporary workaround, remove core file
#
[ -f /core ] && rm -f /core

#
# Add physical swap.
#
/sbin/swapadd -1

#
# Mount the fd file systems if mount point exists.
#
readvfstab /dev/fd < $vfstab
if [ "$mountp" -a -d /dev/fd ]; then
	mountfs - /dev/fd - - - || exit $SMF_EXIT_ERR_FATAL
fi

# Clean up existing /etc/dfs/sharetab as there are no shared file systems
# at this point. This also takes care of a corrupt sharetab.

if [ -f /etc/dfs/sharetab ]; then
	> /etc/dfs/sharetab
fi

exit $SMF_EXIT_OK
