#!/bin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright (c) 2008, 2011, Oracle and/or its affiliates. All rights reserved.
#

# Turn on I/O tracing if requested and possible
trace=`/sbin/devprop -s trace`
if [ "${trace}" = "on" ]; then
	outputfile="/system/volatile/traceout"
	echo "Enabling I/O Tracing ..." > /dev/console
	/usr/dtrace/DTT/Bin/iosnoop -Deg > "${outputfile}" &
	# Wait for iosnoop to actually initialize
	until [[ -s ${outputfile} ]]
	do
		: # shell no-op
	done
fi

exit $SMF_EXIT_OK
