#!/sbin/sh
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Script to invoke sysidns, sysidsys, sysidroot and sysidpm, which complete
# configuration of various system attributes.
#

. /lib/svc/share/smf_include.sh
. /lib/svc/share/fs_include.sh

if [ -f /.livecd ]
then
	# Remove the SMF repository backup as it is not
	# required in a LiveCD.
	# 
	/usr/bin/rm -f /etc/svc/repository-boot*

	# Mount /root home directory onto swap
	mountfs -O /root tmpfs - swap || exit $SMF_EXIT_ERR_FATAL
	cd /.cdrom/root
	find . -print | cpio -pmud /root

	# Mount /jack home directory onto swap
	mountfs -O /jack tmpfs - swap || exit $SMF_EXIT_ERR_FATAL
	cd /.cdrom/jack
	find . -print | cpio -pmud /jack

	#
	# Setup ICE-unix
	#
	/usr/bin/mkdir /tmp/.ICE-unix
	/usr/bin/chown root:root /tmp/.ICE-unix
	/usr/bin/chmod 1777 /tmp/.ICE-unix
fi

exit $SMF_EXIT_OK
