#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#
# Copyright (c) 1984, 1986, 1987, 1988, 1989 AT&T.
# All rights reserved.
#

# Make sure that the libraries essential to this stage of booting can be found.
LD_LIBRARY_PATH=/lib; export LD_LIBRARY_PATH

#
# Set flags to indicate whether we are in LiveCD or AI environment
#
LIVECD=0
AUTOINSTALL=0
MOUNTED=0
[ -f /.livecd ] && LIVECD=1
[ -f /.autoinstall ] && AUTOINSTALL=1

PRTCONF=/usr/sbin/prtconf
SED=/usr/bin/sed
CUT=/usr/bin/cut

libc_mount() {
	#
	# If there is an optimized libc available in /usr that fits this
	# processor, mount it on top of the base libc.
	#
	MOE=`/usr/bin/moe -32 '/usr/lib/libc/$HWCAP'`
	if [ -n "$MOE" ]; then
		/usr/sbin/mount | egrep -s "^/lib/libc.so.1 on "
		if [ $? -ne 0 ]; then
			/usr/sbin/mount -O -F lofs $MOE /lib/libc.so.1
		fi
	fi
}

# This mount function is sun4v only. It may be melded with the sun4u-us3
# version later.
sun4v_libc_psr_mount() {
	LIBC_MOE_32=`/usr/bin/moe -32 /platform/$PLAT/lib/libc_psr/'$HWCAP'`
	if [ -n "$LIBC_MOE_32" ]; then
		/usr/sbin/mount |
		    egrep -s "^/platform/[^/]*/lib/libc_psr.so.1 on "
		if [ $? -ne 0 ]; then
			/usr/sbin/mount -O -F lofs $LIBC_MOE_32 \
			    /platform/$PLAT/lib/libc_psr.so.1
		fi
	fi

	LIBC_MOE_64=`/usr/bin/moe -64 \
	    /platform/$PLAT/lib/sparcv9/libc_psr/'$HWCAP'`
	if [ -n "$LIBC_MOE_64" ]; then
		/usr/sbin/mount |
		    egrep -s "^/platform/[^/]*/lib/sparcv9/libc_psr.so.1 on "
		if [ $? -ne 0 ]; then
			/usr/sbin/mount -O -F lofs $LIBC_MOE_64 \
			    /platform/$PLAT/lib/sparcv9/libc_psr.so.1
		fi
	fi
}

# This is specific to sun4u[-us3].
# try to intelligently handle the various ways that a hwcap library can
# be present for libc_psr for sun4u.
sun4u_libc_psr_mount() {
	# first look for $PLAT specific
	# the string $HWCAP is not an env var but part of the argument to moe
	LIBC_MOE_32=`/usr/bin/moe -32 /platform/$PLAT/lib/libc_psr/'$HWCAP'`
	if [ -n "$LIBC_MOE_32" ]; then
		/usr/sbin/mount |
		    egrep -s "^/platform/$PLAT/lib/libc_psr.so.1 on "
		if [ $? -ne 0 ]; then
			/usr/sbin/mount -O -F lofs $LIBC_MOE_32 \
			    /platform/$PLAT/lib/libc_psr.so.1
		fi
	else
		# try the 'generic' one under $ARCH
		LIBC_MOE_32=`/usr/bin/moe -32 \
		    /platform/$ARCH/lib/libc_psr/'$HWCAP'`
		if [ -n "$LIBC_MOE_32" ]; then
			/usr/sbin/mount |
			    egrep -s "^/platform/$ARCH/lib/libc_psr.so.1 on "
			if [ $? -ne 0 ]; then
				/usr/sbin/mount -O -F lofs $LIBC_MOE_32 \
				    /platform/$ARCH/lib/libc_psr.so.1
			fi
		fi

	fi

	# now repeat for 64 bit.

	LIBC_MOE_64=`/usr/bin/moe -64 \
	    /platform/$PLAT/lib/sparcv9/libc_psr/'$HWCAP'`
	if [ -n "$LIBC_MOE_64" ]; then
		/usr/sbin/mount |
		    egrep -s "^/platform/$PLAT/lib/sparcv9/libc_psr.so.1 on "
		if [ $? -ne 0 ]; then
			/usr/sbin/mount -O -F lofs $LIBC_MOE_64 \
			    /platform/$PLAT/lib/sparcv9/libc_psr.so.1
		fi
	else
		# now try $ARCH version
		LIBC_MOE_64=`/usr/bin/moe -64 \
		    /platform/$ARCH/lib/sparcv9/libc_psr/'$HWCAP'`
		if [ -n "$LIBC_MOE_64" ]; then
			/usr/sbin/mount |
			    egrep -s \
			    "^/platform/$ARCH/lib/sparcv9/libc_psr.so.1 on "
			if [ $? -ne 0 ]; then
				/usr/sbin/mount -O -F lofs $LIBC_MOE_64 \
				    /platform/$ARCH/lib/sparcv9/libc_psr.so.1
			fi
		fi
	fi
}

#
# Most of the operations in this script are only necessary in the global
# zone but due to the way initialization scripts like this are packaged,
# it needs to currently exist for all zones.
#
if [ "${_INIT_ZONENAME:=`/sbin/zonename`}" != "global" ]; then
	libc_mount
	exit 0
fi

. /lib/svc/share/smf_include.sh
. /lib/svc/share/fs_include.sh


if [ $LIVECD = 1 -o $AUTOINSTALL = 1 ]; then
	#
	# Remount root RW
	#
	echo "\rRemounting root read/write" > /dev/msglog
	ISA_INFO=`/sbin/uname -p`
	if [ $ISA_INFO = "sparc" ]
	then
		# ramdisk is differently labeled in sparc vs x86
		/sbin/mount -o remount,rw /devices/ramdisk-root:a /
	else
		# x86 label
		/sbin/mount -o remount,rw /devices/ramdisk:a /
	fi


	#
	# Workaround for devfs lazy init. The sd nodes are not
	# created till you try to access them.
	#
	echo "Probing for device nodes ..." > /dev/msglog

	ls -lR /devices/* > /dev/null
fi

if [ $LIVECD = 1 ]; then
	volumeid=`cat /.volumeid`

	echo "\rPreparing live image for use" >/dev/msglog

	# Determine if any of the USB devices contains a UFS filesystem.
	# For devices that do, attempt to mount them to see if the 
	# compressed /usr filesystem exists

	/sbin/listusb | while read dev rdev
	do
		/usr/lib/fs/ufs/fstyp $rdev 2>&1 | grep "^ufs$"
		if [ $? -eq 0 ]
		then
			/sbin/mount -F ufs -o nologging,noatime $dev /.cdrom || break
			if [ -f /.cdrom/solaris.zlib ]
			then
				echo "" > /.liveusb
				break
			else
				/sbin/umount -f $dev
				continue
			fi
		fi
	done

	# ..Else look for CD
	[ ! -f /.liveusb ] && /sbin/listcd | while read dev rdev
	do
		/usr/lib/fs/hsfs/fstyp -v $rdev 2>&1 | grep "Volume id: $volumeid" > /dev/null
		if [ $? -eq 0 ]
		then
			/sbin/mount -F hsfs -o ro $dev /.cdrom || break
		fi
	done

	# Check if mount of /.cdrom failed.
	/sbin/mount | grep "^/.cdrom"
	if [ $? -ne 0 ]
	then
		echo "** FATAL **: Unable to access media"
		exit $SMF_EXIT_ERR_FATAL
	fi

	# Explictly create lofi devices for solaris.zlib and 
	# solarismisc.zlib

	
	#
	# Can not mount solaris.zlib using just the mount command,
	# because the mount command enforces nosetuid, and /usr
	# needs to have the setuid capability.
	#
	/usr/sbin/lofiadm -a /.cdrom/solaris.zlib /dev/lofi/1 || break
	/sbin/mount -F hsfs -o ro /dev/lofi/1 /usr
	if [ $? -ne 0 ]
	then
		echo "/usr MOUNT FAILED!" 
		exit $SMF_EXIT_ERR_FATAL
	fi


	/sbin/mount -F hsfs -o ro /.cdrom/solarismisc.zlib /mnt/misc
	if [ $? -ne 0 ]
	then
		echo "/mnt/misc MOUNT FAILED!"
		exit $SMF_EXIT_ERR_FATAL
	fi

	/sbin/mount -o ro /.cdrom/pkg.zlib /mnt/pkg
	if [ $? -ne 0 ]
	then
		echo "/mnt/pkg MOUNT FAILED!"
		exit $SMF_EXIT_ERR_FATAL
	fi

	MOUNTED=1
	echo "Done mounting Live image" > /dev/msglog
elif [ $AUTOINSTALL = 1 ]; then
	echo "Preparing automated install image for use" > /dev/msglog

	# Prime the network
	/sbin/dhcpagent -a

	# For SPARC get the dhcp variable Rootpath to get the install media.
	# For X86, get the install media from the menu.lst 
	if [ "$ISA_INFO" = "sparc" ]; then
		MEDIA=`/sbin/dhcpinfo Rootpath`
	else
		# Get the install media data to use in http url
		MEDIA=`/usr/sbin/prtconf -v /devices | \
	    	    /usr/bin/sed -n '/install_media/{;n;p;}' | \
		    /usr/bin/cut -f 2 -d \'`

	fi

	#
	# Translate to valid url - it is dummy operation for now
	# since it is assumed that complete and valid URL was provided
	#
	url=$MEDIA
	if [ -z "$url" ]
	then
		echo "Couldn't determine source of automated install image" > \
		    /dev/msglog
		exit $SMF_EXIT_ERR_FATAL
	fi

	# Mount /tmp to download files
	/usr/lib/fs/tmpfs/mount swap /tmp
	if [ $? -ne 0 ]
	then
		echo "Mounting swap FAILED!" > /dev/msglog
		exit $SMF_EXIT_ERR_FATAL
	fi

	# Download compressed '/usr' and store to tmp
	echo "Downloading solaris.zlib archive" > /dev/msglog
	usr_fs="$url/solaris.zlib"
	/usr/bin/wget $usr_fs -O /tmp/solaris.zlib > \
	    /dev/msglog 2> /dev/msglog
	if [ $? -ne 0 ]
	then
		echo "FAILED" > /dev/msglog
		exit $SMF_EXIT_ERR_FATAL
	fi

	# Download rest of AI net image and store to tmp
	echo "Downloading solarismisc.zlib archive" > /dev/msglog
	misc_fs="$url/solarismisc.zlib"
	/usr/bin/wget $misc_fs -O /tmp/solarismisc.zlib > \
	    /dev/msglog 2> /dev/msglog
	if [ $? -ne 0 ]
	then
		echo "FAILED" > /dev/msglog
		exit $SMF_EXIT_ERR_FATAL
	fi

	# download the install.conf file to get the service name for SPARC
	if [ "$ISA_INFO" = "sparc" ]; then
		install_conf="$url/install.conf"
		/usr/bin/wget $install_conf -O /tmp/install.conf > \
		    /dev/msglog 2> /dev/msglog
		if [ $? -ne 0 ]; then
			echo "FAILED" > /dev/msglog
			exit $SMF_EXIT_ERR_FATAL
		fi
	fi

	# Lofi mount these archives to /usr and /mnt/misc respectively
	/sbin/mount -F hsfs /tmp/solaris.zlib /usr
	if [ $? -ne 0 ]
	then
		echo "Couldn't mount /usr" > /dev/msglog
		exit $SMF_EXIT_ERR_FATAL
	fi

	/sbin/mount -F hsfs /tmp/solarismisc.zlib /mnt/misc
	if [ $? -ne 0 ]
	then
		echo "Couldn't mount /mnt/misc" > /dev/msglog
		exit $SMF_EXIT_ERR_FATAL
	fi
	MOUNTED=1
	echo "Done mounting automated install image" > /dev/msglog

	#
	# set keyboard layout to 'US-English'
	# This is just an interim solution.
	# For long term, keyboard layout will be defined
	# in AI manifest and set in ICT phase
	#
	/usr/bin/kbd -s US-English
fi

# If archives were not mounted, complain and exit
if [ $MOUNTED -ne 1 ] ; then
	if [ $LIVECD = 1 ] ; then
		echo "** FATAL **: Unable to mount Live image!" > /dev/msglog
	elif [ $AUTOINSTALL = 1 ] ; then
		echo "Unable to mount the autoinstall image" > /dev/msglog
	fi
    exit $SMF_EXIT_ERR_FATAL
fi

#
# Root is already mounted (by the kernel), but still needs to be
# checked, possibly remounted and entered into mnttab. First
# mount /usr read only if it is a separate file system. This must
# be done first to allow utilities such as fsck and setmnt to
# reside on /usr minimizing the space required by the root file
# system.
#
readvfstab "/usr" < $vfstab
if [ -n "$mountp" ]; then
	if [ "$fstype" = cachefs ]; then
		#
		# Mount without the cache initially.  We'll enable it
		# later at remount time.  This lets us avoid
		# teaching the statically linked mount program about
		# cachefs.  Here we determine the backfstype.
		# This is not pretty, but we have no tools for parsing
		# the option string until we get /usr mounted...
		#
		case "$mntopts" in
		*backfstype=nfs*)
			cfsbacktype=nfs
			;;
		*backfstype=hsfs*)
			cfsbacktype=hsfs
			;;
		*)
			msg='invalid vfstab entry for /usr'
			echo $msg
			echo "$SMF_FMRI:" $msg >/dev/msglog
			cfsbacktype=nfs
			;;
		esac
		mountfs - /usr $cfsbacktype ro $special ||
		    exit $SMF_EXIT_ERR_FATAL
	else
		#
		# Must use -o largefiles here to ensure the
		# read-only mount does not fail as a result of
		# having a large file present on /usr. This gives
		# fsck a chance to fix up the largefiles flag
		# before we remount /usr read-write.
		#
		if [ "x$mntopts" = x- ]; then
			mntopts='ro,largefiles'
		else
			checkopt largefiles $mntopts
			if [ "x$option" != xlargefiles ]; then
				mntopts="largefiles,$mntopts"
			fi

			checkopt ro $mntopts
			if [ "x$option" != xro ]; then
				mntopts="ro,$mntopts"
			fi

			#
			# Requesting logging on a read-only mount
			# causes errors to be displayed, so remove
			# "logging" from the list of options for now.
			# The read-write mount performed later will
			# specify the logging option if appropriate.
			#

			checkopt logging $mntopts
			if [ "x$option" = xlogging ]; then
				mntopts="$otherops"
			fi
		fi

		mountfs -O /usr $fstype $mntopts - || exit $SMF_EXIT_ERR_FATAL
	fi
fi

#
# Also mount /boot now so that things like keymap.sh can access
# boot properties through eeprom.  Readonly isn't required because
# /boot (and other pcfs filesystems) aren't fsck'ed at boot yet.
# Also, we don't account for caching /boot as it must be on a local
# disk.  So what's in vfstab is fine as it stands; just look to see
# if it's there and avoid the mount if not.
#
readvfstab "/boot" < $vfstab

if [ -n "$mountp" ]; then
	mountfs - /boot $fstype $mntopts - || exit $SMF_EXIT_ERR_FATAL
fi

#
# Update kernel driver.conf cache with any additional driver.conf
# files found on /usr, and device permissions from /etc/minor_perm.
#
/usr/sbin/devfsadm -I -P

[ -f /etc/.dynamic_routing ] && /usr/bin/rm -f /etc/.dynamic_routing

libc_mount

# 
# Discover architecture and find and mount optimal libc_psr 
#  
PLAT=`/usr/bin/uname -i` 
ARCH=`/usr/bin/uname -m` 
if [ "$ARCH" = "sun4v" ]; then 
	sun4v_libc_psr_mount 
elif [ "$ARCH" = "sun4u" ]; then 
	if [ -h /platform/$PLAT/lib/libc_psr.so.1 ]; then 
		LINKSTO=`/usr/bin/ls -l /platform/$PLAT/lib/libc_psr.so.1 | 
			/usr/bin/awk '{print $NF}'` 
		if [ "$LINKSTO" = "../../sun4u-us3/lib/libc_psr.so.1" ]; then 
			ARCH=sun4u-us3 
		fi
	fi
	sun4u_libc_psr_mount 
fi

if [ $LIVECD = 1 -o $AUTOINSTALL = 1 ]
then
	/usr/bin/rm -f /etc/svc/repository-boot*

	# Mount opt
	/usr/sbin/mount -F lofs /mnt/misc/opt /opt
	
	#
	# Update runtime linker cache
	#
	if [ -f /etc/crle.conf ]
	then

		PATH=/usr/foss/bin:/usr/foss/firefox/bin:/usr/foss/thunderbird/bin:/sbin:/usr/sbin:/usr/bin:/usr/ccs/bin:/usr/X11R6/bin:/opt/DTT/bin
		export PATH

		LD_LIBRARY_PATH=/usr/foss/lib:/lib:/usr/lib:/usr/sfw/lib:/usr/X11R6/lib
		export LD_LIBRARY_PATH

		. /etc/crle.conf
		#/usr/bin/crle $CRLE_OPTS
	fi
fi

if [ $LIVECD = 1 ]
then
	#
	# Determine if we should beep to let users with visual
	# impairments know that they are being queried for information.
	#
	assistive_tech=`$PRTCONF -v /devices | \
	    $SED -n '/assistive_tech/{;n;p;}' | $CUT -f 2 -d\'`

	#
	# Ask user to configure Keyboard Layout
	#
	TERM=sun-color
	export TERM
	exec </dev/console >/dev/console 2>&1
	if [ "x$assistive_tech" != "x" ] ; then
		printf "\\a"
	fi
	kbd -s

	#
	# Ask user to configure Language
	#
	if [ "x$assistive_tech" != "x" ] ; then
		printf "\\a"
	fi
	/usr/sbin/set_lang

	# /usr/bin/setup.sh
	livemode=`prtconf -v /devices|sed -n '/livemode/{;n;p;}'|cut -f 2 -d\'`
	if [ "$livemode" = "text" ]; then
		/usr/sbin/svcadm disable -t application/graphical-login/gdm
	else
		[ "$livemode" = "vesa" ] && cp /.cdrom/jack/xorg.conf.vesa /etc/X11/xorg.conf
		/usr/sbin/svcadm enable application/graphical-login/gdm
	fi

fi

exit 0
