#!/bin/ksh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

#
# This script creates a bootable ISO image based on a given package image
# area.

if [ "$#" != "2" ] ; then
	echo "Usage: $0 client_socket_name build_area_path"
	exit 1
fi

SOCK_NAME=$1
PKG_IMG_PATH=$2/build_data/pkg_image
if [ ! -d ${PKG_IMG_PATH} ] ; then
        echo "Image package area ${PKG_IMG_PATH} is not valid"
        exit 1
fi

OUTPUT_PATH=$2/media
DISTRO_NAME=`/bin/ManifestRead ${SOCK_NAME} "name"`

if [ "XX${OUTPUT_PATH}" = "XX" ] ; then
	echo "Output path is not specified in the manifest"
	exit 1
fi

if [ ! -d ${OUTPUT_PATH} ] ; then
	/bin/mkdir -p ${OUTPUT_PATH}
fi

DIST_ISO=${OUTPUT_PATH}/${DISTRO_NAME}.iso

echo "Making final ISO image"

/bin/cd ${PKG_IMG_PATH}
if [ "$?" != "0" ] ; then
	echo "Unable to change directory to ${PKG_IMG_PATH}"
	exit 1
fi

/bin/rm -f $DIST_ISO

/bin/mkisofs -o $DIST_ISO -b boot/grub/stage2_eltorito -c .catalog \
    -no-emul-boot -boot-load-size 4 -boot-info-table -N -l -R -U \
    -allow-multidot -no-iso-translate -cache-inodes -d -D -V \
    "${DISTRO_NAME}" "${PKG_IMG_PATH}"

if [ "$?" != "0" ] ; then
	echo "FAILURE: mkisofs of $DIST_ISO failed"
	exit 1	
fi

exit 0

