#!/bin/ksh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

# =============================================================================
# =============================================================================
# pre_bootroot_pkg_image_mod
#
# Customizations to the package image area before bootroot construction begins.
# =============================================================================
# =============================================================================

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Main
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Customizations to the package image area before bootroot construction begins.
# This script must be called after the package image area is populated.
# 
# Args:
#   MFEST_SOCKET: Socket needed to get manifest data via ManifestRead object
#
#   BUILD_AREA: Build area
#
# Note: Finalizer scripts are called with at least these two args.  However,
# only the BUILD_AREA arg is actually used by this script.

# Note: This assumes a populated pkg_image area exists at the location
#		${PKG_IMG_PATH}.
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

RM=/bin/rm

if [ "$#" != "2" ] ; then
	print -u2 "Usage: $0: pre_bootroot_pkg_image_mod: Requires 2 args: " \
	    "Reader socket, build area mntpt"
	exit 1
fi

PKG_IMG_PATH=$2/build_data/pkg_image
if [ ! -d $PKG_IMG_PATH ] ; then
	print -u2 "$0: Image package area $PKG_IMG_PATH is not valid"
	exit 1
fi

#
# Remove the indices, from the IPS data directory, if any,
# since they are taking up a lot of space, and
# pkg search will work without them.
#
${RM} -rf $PKG_IMG_PATH/var/pkg/index

exit 0
