#!/bin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Registers the operating system into the service tag registry

. /lib/svc/share/smf_include.sh

stclient=/usr/bin/stclient

urn="SOSZ9-609-ZZZZ"

if [ -x ${stclient} ]; then
	${stclient} -f -t "${urn}" 1>/dev/null 2>&1
	if [ $? -ne 0 ]; then
		# Get full release string from /etc/release
		# and parse into product name and version
		fullname=`head -1 /etc/release | sed 's/^ *//'`
		prodname=`echo ${fullname} | cut -f 1 -d ' '`
		prodvers=`echo ${fullname} | cut -f 2 -d ' '`
		${stclient} -a \
			-p "${prodname} ${prodvers}" \
			-e "${prodvers}" \
			-t "${urn}" \
			-S SUNWstosreg \
			-F "urn:uuid:596ffcfa-63d5-11d7-9886-ac816a682f92" \
			-P "Solaris Operating System" \
			-m "Sun Microsystems" \
			-A "`/bin/uname -p`" \
			-z "`/bin/zonename`" 1>/dev/null
	fi
fi

exit $SMF_EXIT_OK
