#!/bin/ksh

#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END

# Copyright 2005 Sun Microsystems, Inc.  All rights reserved. 
# Use is subject to license terms.
# This script attempts to detect legacy OS's installed on the system and
# generate GRUB boot menu entries for them. Currently this is know to
# work for NT derived Windows systems (ntfs or FAT fs on IFS partitions)
# as well as DOS/Win9x systems (FAT on FAT partitions). It is likely to
# work for OS/2 on IFS partitions. Linux, particularly on extended
# partitions is not supported at this point. For every un-understood
# partition type that is potentially bootable a comment is generated
# that identifies it's Solaris device name, the partition type as well
# as the GRUB device name to give an educated user as much information
# as possible to generate their own entry.


# generate a chainload entry for a specific OS entry <grub device> <title>
#
entry()
{
	root=$1
	title=$2
	active=$3

	grep -v ^# $GRUBMENU | grep $root > /dev/null
	if [ $? = 1 ] ; then
		printf "\ntitle $title\n" >> $GRUBMENU
		printf "\trootnoverify $root\n" >> $GRUBMENU
		printf "\tchainloader +1\n" >> $GRUBMENU

		if [ "$active" = "makeactive" ] ; then
			printf "\tmakeactive\n" >> $GRUBMENU
		fi
	fi
}

# process a FAT partition
#
handle_fat()
{
	root=$3

	entry $root Windows
}

# process an IFS partition
#
handle_ifs()
{
	dev=$1
	rdev=$2
	root=$3

	sig=`strings $rdev 2> /dev/null | head -1 | awk '{ print $1 }'`
	if [ "$sig" = "NTFS" ] ; then
		entry $root "Windows"
	else
		entry $root OS/2
	fi
}

# process a Solaris partition - this only deals with DCA based Solaris
# instances as GRUB based Solaris instances are handled directly by bootadm
#
handle_solaris()
{
	dev=$1
	rdev=$2
	root=$3

	tmp=/tmp/mnt$$
	mkdir $tmp

	for i in 0 1 3 4 5 6 7 ; do
		fs=`fstyp ${dev}s$i 2> /dev/null`
		if [ "$fs" = "ufs" ] ; then
			mount -o ro ${dev}s$i $tmp 2> /dev/null
			if [ $? != 0 ] ; then
				continue
			fi

			if [ -f $tmp/etc/release ] ; then
				if [ ! -f $tmp/platform/i86pc/multiboot ] &&
				    [ -f $tmp/boot/solaris/boot.bin ] ; then
					release=`head -1 $tmp/etc/release | \
					    sed "s/^[	 ]*//"`
					entry $root "$release" makeactive
				fi
			fi
			umount $tmp > /dev/null 2>&1
		fi
	done

	rmdir $tmp
}

# process a Solaris x86-boot partition
#
handle_x86boot()
{
	dev=$1
	rdev=$2
	root=$3

	tmp=/tmp/mnt$$
	mkdir $tmp
	
	fs=`fstyp $rdev 2> /dev/null`
	device=""
	if [ "$fs" = "pcfs" ] ; then
		mount -o ro -F pcfs ${dev}p$partition $tmp 2> /dev/null
		device=`grep "^setprop bootpath " $tmp/solaris/bootenv.rc \
		    2> /dev/null | awk '{ print $3 }' | sed s/\'//`
		umount $tmp 2> /dev/null 2>&1
	fi

	if [ -z "$device" ] ; then
		rmdir $tmp
		return
	fi

	fs=`fstyp /devices/$device 2> /dev/null`
	if [ "$fs" = "ufs" ] ; then
		mount -o ro /devices/$device $tmp 2> /dev/null
		if [ $? != 0 ] ; then
			continue
		fi

		if [ -f $tmp/etc/release ] ; then
			if [ ! -f $tmp/platform/i86pc/multiboot ] &&
			    [ -f $tmp/boot/solaris/boot.bin ] ; then
				release=`head -1 $tmp/etc/release | \
				    sed "s/^[	 ]*//"`
				entry $root "$release"
			fi
		fi
		umount $tmp > /dev/null 2>&1
	fi

	rmdir $tmp
}

# process a diag (usually DOS based) partition
#
handle_diag()
{
	root=$3
	entry $root "Diagnostic Partition"
}

# generate a comment for an un-understood partition
#
unhandled()
{
	disk=$1
	partition=$2
	root=$3
	id=$4

	grep $root $GRUBMENU > /dev/null
	if [ $? = 1 ] ; then
		printf "\n# Unknown partition of type $id found " >> $GRUBMENU
		printf "on $disk partition: $partition\n# It " >> $GRUBMENU
		printf "maps to the GRUB device: $root .\n" >> $GRUBMENU
	fi
}


# begin main
#

if [ -f "$1" ] ; then
	GRUBMENU=$1
else
	printf "usage: $0 <grub menu file>\n" >&2
	exit 1
fi

if [ ! -f /var/run/solaris_grubdisk.map ] && 
    [ -x /boot/solaris/bin/create_diskmap ] ; then
	/boot/solaris/bin/create_diskmap
fi

for disk in /dev/rdsk/*p0 ; do
	typeset -i partition=1
	typeset -i gpart

	for id in `fdisk -W - $disk 2> /dev/null | grep -v "^*" | \
	    awk '{ print $1 }'` ; do
		dev=`echo $disk | sed s#/rdsk/#/dsk/# | sed s/p0$//`
		rdev=`echo $disk | sed s/p0$/p$partition/`
		gpart=$partition-1
		ctd=`basename $disk | sed s/p0$//`
		grep $ctd /var/run/solaris_grubdisk.map > /dev/null 2> /dev/null
		if [ $? = 0 ] ; then
			gdisk=`grep $ctd /var/run/solaris_grubdisk.map | \
			    awk '{ print $1 }'`
		else
			gdisk=0
		fi
		root="(hd$gdisk,$gpart)"

		case $id in
			7)	handle_ifs $dev $rdev $root ;;
			11)	handle_fat $dev $rdev $root ;;
			12)	handle_fat $dev $rdev $root ;;
			18)	handle_diag $dev $rdev $root ;;
			23)	handle_ifs $dev $rdev $root ;;
			28)	;; # hidden FAT32 must ignore
			130)	handle_solaris $dev $rdev $root ;;
			190)	handle_x86boot $dev $rdev $root ;;
			191)	handle_solaris $dev $rdev $root ;;
			222)	handle_diag $dev $rdev $root ;;
			*)	unhandled $disk $partition $root $id ;;
		esac

		partition=$partition+1
	done
done
