#!/bin/ksh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

# =============================================================================
# =============================================================================
# ai_post_bootroot_configure
#
# pkg_image area modifications specific for automated install, to be made 
# after the bootroot is built.
# =============================================================================
# =============================================================================

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Main
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Perform pkg_image area modifications specific for automated install after the
# bootroot is built.  This finalizer script is to be called after the bootroot
# has been configured.
# 
# Args:
#   MFEST_SOCKET: Socket needed to get manifest data via ManifestRead object
#
#   PKG_IMG_PATH: Package image area
#
#   TMP_DIR: Temporary directory to contain the bootroot file (not used)
#
#   BR_BUILD: Area where bootroot is put together (not used)
#
#   MEDIA_DIR: Area where the media is put (not used)
#
# Note: Although finalizer scripts receive at least the five args above, this
# script uses only MFEST_SOCKET and PKG_IMG_PATH
#
#
# Note: This assumes bootroot is built and pkg_image area is intact.
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Verify argument count
if [ $# != 5 ] ; then
	print -u2 "$0: Requires 5 args:"
	print -u2 "    Reader socket, pkg_image mntpt, tmp dir,"
	print -u2 "    bootroot build area, media area"
	exit 1
fi

# Get commandline args.  First 5 are passed to all finalizer scripts.

PKG_IMG_PATH=$2
if [ ! -d ${PKG_IMG_PATH} ] ; then
	echo "PKG_IMG_PATH not set"
	print -u2 "$0: Image package area ${PKG_IMG_PATH} is not valid"
	exit 1
fi

# This is the full path to the top of the bootroot
BR_BUILD=$4
if [ ! -d ${BR_BUILD} ] ; then
	print -u2 "$0: bootroot build area $BR_BUILD is invalid."
	exit 1
fi

if [ ! -f ${BR_BUILD}/platform/i86pc/multiboot ] ; then
	print -u2 "$0: /platform/i86pc/multiboot missing from the bootroot!"
	exit 1
fi	

# Copy /platform as well as /platform/i86pc/multiboot
if [ -d ${PKG_IMG_PATH}/platform ] ; then
	cp -r ${PKG_IMG_PATH}/platform ${PKG_IMG_PATH}/boot
	cp ${BR_BUILD}/platform/i86pc/multiboot ${PKG_IMG_PATH}/boot
	exit 0
fi

exit 1
